apiVersion: v1
kind: Service
metadata:
  name: chatnoir-chat-sentence-retrieval-bm25-cw22
  namespace: services-chatnoir
spec:
  selector:
    app: chatnoir-chat-sentence-retrieval-bm25-cw22
  ports:
  - name: ui
    port: 5000
    protocol: TCP
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatnoir-chat-sentence-retrieval-bm25-cw22
  namespace: services-chatnoir
spec:
  selector:
    matchLabels:
      app: chatnoir-chat-sentence-retrieval-bm25-cw22
  replicas: 1
  template:
    metadata:
      labels:
        app: chatnoir-chat-sentence-retrieval-bm25-cw22
    spec:
      containers:
      - name: chatnoir-chat-sentence-retrieval-bm25-cw22
        image: registry.webis.de/code-lib/public-images/chatnoir-chat-sentence-retrieval:0.0.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: 10Gi
            cpu: 1
          limits:
            memory: 15Gi
            cpu: 2
        volumeMounts:
          - mountPath: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-clueweb22/disk-category-b/
            name: cw22
            readOnly: true
          - mountPath: /root/.ir_datasets/
            name: irds
      volumes:
      - name: cw22
        hostPath:
          path: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-clueweb22/disk-category-b/
      - name: irds
        hostPath:
          path: /mnt/ceph/tira/state/ir_datasets
