# Generated by Django 4.2.4 on 2023-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAndResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('md5_hash_of_request', models.CharField(db_index=True, max_length=280)),
                ('seed', models.CharField(db_index=True, max_length=50)),
                ('request_text', models.TextField(default='')),
                ('response_text', models.TextField(default='')),
            ],
        ),
    ]
