# Generated by Django 4.2.4 on 2023-08-21 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestandresponsecache',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requestandresponsecache',
            name='endpoint',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
