# Generated by Django 4.2.4 on 2023-10-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0002_requestandresponsecache_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=150)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chatnoir_chat.chat')),
            ],
        ),
    ]
