# Generated by Django 4.2.4 on 2023-10-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0003_chat_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
