# Generated by Django 4.2.4 on 2023-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0004_rename_chat_id_chatmessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='display_name',
            field=models.CharField(default='Unnamed Chat', max_length=50),
        ),
    ]
