# Generated by Django 4.2.6 on 2023-10-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0005_chat_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBackends',
            fields=[
                ('backend_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Unnamed Backend', max_length=50)),
                ('description', models.CharField(default='Please add a description.', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
