# Generated by Django 4.2.6 on 2023-10-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0006_custombackends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombackends',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='custombackends',
            name='description',
        ),
        migrations.RemoveField(
            model_name='custombackends',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='custombackends',
            name='user_id',
        ),
    ]
