# Generated by Django 4.2.7 on 2023-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0009_custombackends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
