# Generated by Django 4.2.7 on 2023-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatnoir_chat', '0010_chat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
