FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime

RUN apt-get update \
	&& apt-get install -y git \
	&& pip3 install git+https://github.com/huggingface/transformers \
	&& pip3 install flask sentencepiece

