FROM registry.webis.de/code-lib/public-images/chatnoir-chat:0.0.1-basis

ADD gpt2/gpt2-large /workspace/gpt2-large

ENTRYPOINT ["python3", "/workspace/flask_api.py", "--input_model", "/workspace/gpt2-large/"]

